# Anomaaliad

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# Andmestiku sisselugemine

df = pd.read_csv("bolt_cleaned.csv")
df

,order_id_new,order_try_id_new,calc_created,metered_price,upfront_price,distance,duration,gps_confidence,entered_by,b_state,...,device_name,eu_indicator,overpaid_ride_ticket,fraud_score,date,time,day_of_week,day_of_week_nr,month,year
0,22,22,2020-02-02 03:37:31,4.04,10.0,2839,700,1,client,finished,...,Xiaomi Redmi 6,1,0,-1383.0,2020-02-02,03:37:31,Sunday,7,2,2020
1,618,618,2020-02-08 02:26:19,6.09,3.6,5698,493,1,client,finished,...,Samsung SM-G965F,1,0,NaN,2020-02-08,02:26:19,Saturday,6,2,2020
2,657,657,2020-02-08 11:50:35,4.32,3.5,4426,695,1,client,finished,...,Samsung SM-A530F,1,0,-166.0,2020-02-08,11:50:35,Saturday,6,2,2020
3,313,313,2020-02-05 06:34:54,72871.72,NaN,49748,1400,0,client,finished,...,TECNO-Y6,0,1,NaN,2020-02-05,06:34:54,Wednesday,3,2,2020
4,1176,1176,2020-02-13 17:31:24,20032.50,19500.0,10273,5067,1,client,finished,...,Itel W5504,0,0,NaN,2020-02-13,17:31:24,Thursday,4,2,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,3513,3513,2020-03-07 17:42:34,10.89,13.7,15672,1449,1,client,finished,...,HUAWEI LYA-L29,1,0,-286.0,2020-03-07,17:42:34,Saturday,6,3,2020
4939,2192,2192,2020-02-22 18:15:45,8789.28,NaN,5712,1173,0,client,finished,...,Samsung SM-G928F,0,0,NaN,2020-02-22,18:15:45,Saturday,6,2,2020
4940,4051,4051,2020-03-12 23:08:31,7.50,7.4,5303,486,1,client,finished,...,HUAWEI AMN-LX9,1,0,-192.0,2020-03-12,23:08:31,Thursday,4,3,2020
4941,3636,3636,2020-03-08 20:15:04,3.06,8.1,3528,338,1,client,finished,...,TP-Link Neffos X1,1,0,-228.0,2020-03-08,20:15:04,Sunday,7,3,2020
4942,759,759,2020-02-09 07:21:22,29244.10,16000.0,17825,4544,1,client,finished,...,Samsung SM-A260F,0,0,NaN,2020-02-09,07:21:22,Sunday,7,2,2020

## on 20 sõitu, mille puhul on kõik need kategooriad NaN
prediction_price_type

prediction_price_type

upfront_price            

predicted_distance

predicted_duration

change_reason_pricing

In [8]:
cols = [
    "prediction_price_type",
    "upfront_price",
    "predicted_distance",
    "predicted_duration",
    "change_reason_pricing"
]

# Valin read, kus kõik viis väärtust puuduvad
missing_rides = df_clean[
    df_clean[cols].isna().all(axis=1)
]

# Kuvan
missing_rides

,order_id_new,order_try_id_new,calc_created,metered_price,upfront_price,distance,duration,gps_confidence,entered_by,b_state,...,ticket_id_new,rider_app_version,order_state,order_try_state,driver_app_version,driver_device_uid_new,device_name,eu_indicator,overpaid_ride_ticket,fraud_score
64,217,217,2020-02-04 08:07:10,NaN,NaN,6249,2477,1,driver,finished,...,1642,NaN,finished,finished,DA.4.37,977,Xiaomi Redmi 8,1,0,NaN
393,3066,3066,2020-03-02 17:45:17,NaN,NaN,5483,917,1,driver,finished,...,4904,NaN,finished,finished,DA.4.42,1065,HUAWEI EML-L29,1,0,NaN
458,3320,3320,2020-03-06 03:33:52,NaN,NaN,3364,323,0,reseller,finished,...,299,NaN,finished,finished,DA.4.42,1657,HUAWEI CLT-L29,1,0,NaN
513,1166,1166,2020-02-13 14:55:14,NaN,NaN,21997,1742,1,driver,finished,...,4172,CA.5.26,finished,finished,DA.4.37,1226,HUAWEI SLA-L22,1,0,-74.0
779,1759,1759,2020-02-19 00:55:07,NaN,NaN,10309,849,1,reseller,finished,...,3363,NaN,finished,finished,DI.3.32,177,"iPhone8,1",1,0,NaN
998,861,861,2020-02-10 06:52:29,NaN,NaN,1424,416,1,driver,finished,...,2297,NaN,finished,finished,DA.4.37,1732,Samsung SM-G973F,1,0,NaN
1206,1349,1349,2020-02-14 23:08:22,NaN,NaN,11206,1268,1,client,finished,...,2896,CI.4.17,finished,finished,DA.4.31,702,Samsung SM-T295,1,0,-1270.0
1287,2012,2012,2020-02-21 13:24:40,NaN,NaN,3717,713,1,driver,finished,...,3704,NaN,finished,finished,DA.4.39,451,Samsung SM-A530F,1,0,NaN
1340,1112,1112,2020-02-12 23:32:11,NaN,NaN,4114,528,1,driver,finished,...,2622,NaN,finished,finished,DA.4.39,1965,Xiaomi Mi A1,1,0,NaN
1582,460,460,2020-02-06 19:34:43,NaN,NaN,6718,764,1,client,finished,...,1882,CI.3.22,finished,finished,DI.3.33,46,"iPhone8,1",1,0,NaN
1603,2675,2675,2020-02-28 05:10:59,NaN,NaN,3014,2339,1,driver,finished,...,4724,NaN,finished,finished,DA.4.42,1396,Sony G8441,1,0,NaN
1919,3305,3305,2020-03-05 21:29:00,NaN,NaN,15263,1226,1,driver,finished,...,329,NaN,finished,finished,DA.4.42,1237,Xiaomi Redmi 6A,1,0,NaN
2213,1459,1459,2020-02-15 16:18:50,NaN,NaN,4729,685,1,driver,finished,...,3048,CI.4.17,finished,finished,DA.4.39,834,Samsung SM-A705FN,1,0,NaN
2321,834,834,2020-02-09 21:33:13,NaN,NaN,8376,826,1,reseller,finished,...,2277,NaN,finished,finished,DA.4.39,1828,CUBOT_P20,1,0,NaN
2603,2675,2675,2020-02-28 05:10:59,NaN,NaN,3014,2339,1,driver,finished,...,4470,NaN,finished,finished,DA.4.42,1396,Sony G8441,1,0,NaN
2649,844,844,2020-02-10 00:27:54,NaN,NaN,0,0,0,reseller,finished,...,2282,NaN,finished,finished,DA.4.39,912,Samsung SM-G935F,1,0,NaN
2717,3880,3880,2020-03-11 12:47:49,NaN,NaN,18237,5041,1,driver,finished,...,944,NaN,finished,finished,DA.4.42,1408,HUAWEI MAR-LX1A,1,0,NaN
3166,5,5,2020-02-02 00:35:20,NaN,NaN,3486,296,1,reseller,finished,...,1399,NaN,finished,finished,DA.4.37,1269,Samsung SM-G973F,1,0,NaN
4339,1344,1344,2020-02-14 22:11:14,NaN,NaN,2686,500,1,driver,finished,...,2847,NaN,finished,finished,DA.4.37,515,Samsung SM-J510FN,1,0,NaN
4747,4113,4113,2020-03-13 15:21:00,NaN,NaN,19929,2094,1,driver,finished,...,1196,NaN,finished,finished,DA.4.42,1569,Samsung SM-A405FN,1,0,NaN

## Tähelepanekud:
1. Kõigil puuduvad hinnastamisandmed (metered_price ja upfront_price), kuid ülejäänud sõiduinfo on üldiselt olemas
2. overpaid_ride_ticketid puuduvad selles grupis.
3. eu_indicator on kõigil 1 (asuvad EU-s).
4. gps_confidence: 18- sõidul 1 (ehk usaldusväärne), kahel sõidul 0